name: Test ODR
on: [push, pull_request]
jobs:
  test-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Apt install
        run: sudo apt-get install ninja-build
      - name: Pip install
        run: pip install -r test/requirements.txt
      - name: Run  tests
        run: python -m pytest
      - name: Aggregate junit
        run: ./odr_junit.py build/ odr_junit.xml
      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: test-odr_junit.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: odr_junit results

  test-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pip install
        run: pip install -r test/requirements.txt
      - name: Run test
        shell: cmd
        env:
          CC: cl.exe
          CXX: cl.exe
        # TODO: neither ilammy/msvc-dev-cmd nor microsoft/setup-msbuild seems to be working, failing with
        #   Could not find compiler set in environment variable CC: cl.exe
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          python -m pytest
