name: Test ODR
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container: conanio/gcc10:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pip install
        run: pip install -r test/requirements.txt
      # TODO: research why sudo is required, possibly conan container broken?
      - name: Run test in container
        run: |
          cd test
          sudo python -m pytest -sv test.py
